version: '3.8'

services:
  postgres:
    restart: unless-stopped
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    networks:
      - simple-metrics-dev
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8085:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=postgres:5432
      - ADMINER_PLUGINS=enum-types enum-option json-column
    networks:
      - simple-metrics-dev

volumes:
  postgres-data:

networks:
  simple-metrics-dev:
    driver: bridge
